// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmGA9OwMoyixZ8G6q5phwP54BGkijO5Fw',
    appId: '1:996925096071:web:17e91543e198e0b1a2b822',
    messagingSenderId: '996925096071',
    projectId: 'reviewseverywhere-b3eb5',
    authDomain: 'reviewseverywhere-b3eb5.firebaseapp.com',
    storageBucket: 'reviewseverywhere-b3eb5.firebasestorage.app',
    measurementId: 'G-7XFZ9GTJZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp1kOl6OZnutqePWz10huHGueP6bJUazw',
    appId: '1:996925096071:android:08c4536d766bce73a2b822',
    messagingSenderId: '996925096071',
    projectId: 'reviewseverywhere-b3eb5',
    storageBucket: 'reviewseverywhere-b3eb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvChz8SrmNk3LUqFr92sgfgxjM4JenBo',
    appId: '1:996925096071:ios:eb3968bbdabb2df9a2b822',
    messagingSenderId: '996925096071',
    projectId: 'reviewseverywhere-b3eb5',
    storageBucket: 'reviewseverywhere-b3eb5.firebasestorage.app',
    iosBundleId: 'com.reviewseverywhere.review',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOvChz8SrmNk3LUqFr92sgfgxjM4JenBo',
    appId: '1:996925096071:ios:801df65b928aa3a6a2b822',
    messagingSenderId: '996925096071',
    projectId: 'reviewseverywhere-b3eb5',
    storageBucket: 'reviewseverywhere-b3eb5.firebasestorage.app',
    iosBundleId: 'com.example.cards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmGA9OwMoyixZ8G6q5phwP54BGkijO5Fw',
    appId: '1:996925096071:web:8b66f098257619a2a2b822',
    messagingSenderId: '996925096071',
    projectId: 'reviewseverywhere-b3eb5',
    authDomain: 'reviewseverywhere-b3eb5.firebaseapp.com',
    storageBucket: 'reviewseverywhere-b3eb5.firebasestorage.app',
    measurementId: 'G-EKP4T2397Y',
  );
}
